export const items = [
  { name: "Dry bags/keg", weigth: 0, img: "" },
  { name: "Puffy Jacket", weight: 0, img: "" },
  { name: "Swimming Suit", weight: 0, img: "" },
  { name: "Toiletries", weight: 0, img: "" },
  { name: "First aid", weight: 0, img: "" },
  { name: "Soap", weight: 0, img: "" },
  { name: "Lights", weight: 0, img: "" },
  { name: "Face Sun Screen", weight: 0, img: "" },
  { name: "Body Sun Screen", weight: 0, img: "" },
  { name: "Lip Balm", weight: 0, img: "" },
  { name: "Nylon Cord", weight: 0, img: "" },
  { name: "Garbage Bag", weight: 0, img: "" },
  { name: "External Battery", weight: 0, img: "" },
  { name: "Towel", weight: 0, img: "" },
  { name: "Floats", weight: 0, img: "" },
  { name: "Tripod", weight: 0, img: "" },
  { name: "Hat", weight: 0, img: "" },
  { name: "Water Filter", weight: 0, img: "" },
  { name: "Water Pack", weight: 0, img: "" },
  { name: "Snacks", weight: 0, img: "" },
  { name: "Electrolytes", weight: 0, img: "" },
  { name: "Oat Meal x12", weight: 0, img: "" },
  { name: "Power Bars", weight: 0, img: "" },
  { name: "Small Shovel", weight: 0, img: "" },
  { name: "Stove And Fuel", weight: 0, img: "" },
  { name: "Utensils", weight: 0, img: "" },
  { name: "Sun Hat", weight: 0, img: "" },
  { name: "Soap", weight: 0, img: "" },
  { name: "Moisturizer", weight: 0, img: "" },
  { name: "Floss", weight: 0, img: "" },
  { name: "Tooth Brush", weight: 0, img: "" },
  { name: "Tooth Paste", weight: 0, img: "" },
  { name: "Large Pack", weight: 0, img: "" },
  { name: "Small Pack", weight: 0, img: "" },
  { name: "Sleeping Bag", weight: 0, img: "" },
  { name: "Tent", weight: 0, img: "" },
  { name: "Mattress", weight: 0, img: "" },
  { name: "Pillow", weight: 0, img: "" },
  { name: "Rain Jacket", weight: 0, img: "" },
  { name: "Water Shoes", weight: 0, img: "" },
  { name: "underwear", weight: 0, img: "" },
  { name: "tops", weight: 0, img: "" },
  { name: "long pant", weight: 0, img: "" },
  { name: "shorts", weight: 0, img: "" },
  { name: "shocks", weight: 0, img: "" },
  { name: "Insect Repellent", weight: 0, img: "" },
  { name: "Mirror", weight: 0, img: "" },
];

export const images = () => items.map((item) => (item.img ? item.img : null));
